tobe_done : all

!include ../makefile.inc

all :
	cd erlms
	$(MAKE) -f makefile.bor all
	cd ..
	cd erlmsch
	$(MAKE) -f makefile.bor all
	cd ..

clean :
	cd erlms
	$(MAKE) -f makefile.bor clean
	cd ..
	cd erlmsch
	$(MAKE) -f makefile.bor clean
	cd ..


install :
        - copy .\erlms\erlms.exe $(INSTALL_DIR_SKIMMED)
        - copy .\erlmsch\erlmsch.exe $(INSTALL_DIR_SKIMMED)

erlscale : all install