testre TEST.C res  
testre TEST1.C res  
testre TRY.C res  
testre TA.C res  
testre RU.C res  
testre RE.C res  
testre OO.C res  
testre FY.C res  
testre FU.C res  
testre FI.C res  
testre CONCERT.C res  
testre ER.C res  
testre ER1.C res  
testre ESS.C res  
testre FA.C res  
testre FO.C res  
testre DEC.C res  
testre DEC1.C res  
testre DECLAR.C res  
testre DECL.C res  
testre STRUCT.C res  
testre TOTO.C res  
testre TU.C res  
testre DEC2.C res  
testre ESSAI.C res  
testre TZ.C res  
testre TANS1.C res  
testre TY.C res  
testre TW.C res  
testre TWI.C res  
testre REF.C res  
testre ZZ.C res  
testre FUNC.C res  
testre TYPEDEF.C res  
testre CASE.C res  
testre FIFI.C res  
testre FOFO.C res  
testre YY.C res  
testre YYY.C res  
testre ZZZ.C res  
testre FF.C res  
testre ELESSAI.C res  
testre ELESS.C res  
testre ELMAIN.C res  
