all : all_to_do

include makefile.inc

all_to_do :
	@- mkdir $(INSTALL_DIR_SKIMMED) 
	cd pub 
	$(MAKE) -f makefile.dos all
	cd ..
	cd misc 
	$(MAKE) -f makefile.dos all
	cd ..

clean :
	cd pub 
	$(MAKE) -f makefile.dos clean
	cd ..
	cd misc 
	$(MAKE) -f makefile.dos clean
	cd ..

install :
	- mkdir $(INSTALL_DIR)  
	cd pub 
	$(MAKE) -f makefile.dos install
	cd ..
	cd misc 
	$(MAKE) -f makefile.dos install
	cd ..


