!include ./makefile.win

chunkch.exe : $(OBJECTS) 
	$(C_PLUS_LNK) $(LNK_FLAGS) /out:chunk.exe $(OBJECTS) $(CPLUS) $(CHOPB) $(LIBRARY)
    -$(RM) chunkch.exe
    -ren chunk.exe chunkch.exe





