#!/bin/sh
#find suffix of name
emacs=""
flat=""
tableString=""
WIDTH_INDICATION=""
analyzeArg=1

SET_ORDER="" 
# -set ${HOME}/c.set"
while [ $analyzeArg -eq 1 ] ; do
    name=$1
    if [ $name = "-flat" ] ; then
        flat="-flat";
        shift;
    elif [ $name = "-tableString" ] ; then
        tableString="-tableString";
        shift ;
    elif [ $name = "-set" ] ; then
        shift
        SET_ORDER="-set $1"
        shift;
    elif [ $name = "-rightMargin" ] ; then
        shift
        WIDTH_INDICATION="-rightMargin $1"
        shift;
    elif [ $name = "-emacs" ] ; then
        emacs="-emacs";
        shift;
    else
        analyzeArg=0
    fi;
done

#give help if no arguments are given
if [ "$1" = "" ]
then
    echo "usage: $0 filename(s)"
    exit
fi

#find suffix of name
for i in $*
do
    echo "Processing file $i:"

    # suppress tabulations in file
    # deltab $i

    #pretty file
    cpbem $emacs $SET_ORDER $WIDTH_INDICATION $tableString $flat $i $$_res.cpb > $$_error 2>&1
    echo "done"
    cat $$_error

    result=`grep "For details see" $$_error`

    if [ $? != 0 ]
    then
	result=`grep "No Error Found" $$_error`

	if [ $? != 0 ]
	then
	    rm -f res.cpb
            rm $$_error
	    exit 3;
	fi
    fi

    rm $$_error

    #replace original file
    if [ $? != 0 ] ; then
        rm -f $$_res.cpb
        exit $?
    else
        mv $$_res.cpb `realpath $i`
    fi
done

