#!/bin/sh

#find suffix of name
emacs=""
flat=""
tableString=""
WIDTH_INDICATION=""
analyzeArg=1

SET_ORDER=""
# SET_ORDER="-set ${HOME}/c.set"
while [ $analyzeArg -eq 1 ] ; do
    name=$1
    if [ $name = "-flat" ] ; then
        flat="-flat";
        shift;
    elif [ $name = "-tableString" ] ; then
        tableString="-tableString";
        shift ;
    elif [ $name = "-set" ] ; then
        shift
        SET_ORDER="-set $1"
        shift;
    elif [ $name = "-rightMargin" ] ; then
        shift
        WIDTH_INDICATION="-rightMargin $1"
        shift;
    elif [ $name = "-emacs" ] ; then
        emacs="-emacs";
        shift;
    else
        analyzeArg=0
    fi;
done 

name=`basename $1`
suffix=`echo $name | sed 's/.*\.//'`

#suppress tabulations in file
# deltab $1

export file=`realpath $1`
# echo "file : ${file}" 

cp ${file} keep.erl

#if ch use chopb else cplus
if [ $suffix = "ch" ]
then
    chopb $SET_ORDER $tableString ${file} > $2
elif [ $suffix = "CH" ]
then
    chopb $SET_ORDER ${file} > $2
elif [ $suffix = "met" ]
then
    metab ${file} > $2
elif [ $suffix = "MET" ]
then
    metab ${file} > $2
elif [ $suffix = "isl" ]
then
    isl ${file} > $2
elif [ $suffix = "ISL" ]
then
    isl ${file} > $2
elif [ $suffix = "cedit" ]
then
    omt ${file} > $2
elif [ $suffix = "ASN" ]
then
    asnext -b ${file} > $2
elif [ $suffix = "asn" ]
then
    asnext -b ${file} > $2
elif [ $suffix = "MKP" ]
then
    asnext2 -b  ${file} > $2
elif [ $suffix = "mkp" ]
then
    asnext2 -b ${file} > $2
elif [ $suffix = "MKO" ]
then
    asnext2 -b  ${file} > $2
elif [ $suffix = "mko" ]
then
    asnext2 -b ${file} > $2
elif [ $suffix = "java" ]
then
    pjava $flat ${file} > $2
elif [ $suffix = "JAVA" ]
then
    pjava $flat ${file} > $2
elif [ $suffix = "json" ]
then
    prettyJson ${file} > $2
else
    cplus $emacs $tableString $WIDTH_INDICATION $SET_ORDER ${file} > $2
fi
result=$?
if [ $result != 0 ] ; then
    exit $result
fi
if [ $suffix = "asn" -o  $suffix = "ASN" -o  $suffix = "mkp" -o  $suffix = "MKP" -o  $suffix = "mko" -o  $suffix = "MKO" ]
then
    echo "asn pretty printing. No Error Found."
fi

